name: Build aggregator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths: ['aggregator/**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with maven
        working-directory: aggregator/
        run: mvn --batch-mode clean package

      - name: Upload aggregator
        uses: actions/upload-artifact@v4
        with:
          name: aggregator
          path: aggregator/

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download aggregator
        uses: actions/download-artifact@v4
        with:
          name: aggregator

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: aggregator/
          file: aggregator/src/main/docker/Dockerfile.jvm
          push: true
          tags: spoud/kafka-cost-control:latest
